apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mycat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mycat
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: mycat
          image: dilero/k8s-demo:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mycat-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mycat